In [1]:
import numpy as np

In [2]:
def predict(x,w):
    y=np.dot(x,w[1:])+w[0]
    return y

In [3]:
def predict_class(x, w):
    y=np.sign(predict(x,w))
    return y

In [4]:
x = np.array([1,2,5])

In [5]:
x

array([1, 2, 5])

In [6]:
w=np.array([7,2,-1,4])

In [7]:
w

array([ 7,  2, -1,  4])

In [8]:
x.shape

(3,)

In [9]:
w.shape

(4,)

In [10]:
predict(x,w)

27

In [11]:
predict_class(x,w)

1

In [12]:
def perceptron(x,y,lr):
    w=np.zeros(len(x[0])+1)
    for i in range(np.shape(x)[0]):
        w[1:]=w[1:]+ lr*x[i]*(y[i] - predict_class(x[i] ,w))
        w[0]=w[0]+lr*(y[i] - predict_class(x[i] ,w))
    return(w)

In [13]:
x = np.array([[1,2,3],[4,0,-1],[2,9,4],[1,2,1],[2,0,-1],[2,9,5]])

In [14]:
y=np.array([-1,-1,-1,1,1,1])

In [15]:
y

array([-1, -1, -1,  1,  1,  1])

In [16]:
import pandas as pd

In [17]:
data = pd.read_csv('D:/ML/sonar.csv', header=None)

In [18]:
data.head()

0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   

       58      59   60  
0  0.0090  0.0032  1.0  
1  0.0052  0.0044  1.0  
2  0.0095  0.0078  1.0  
3  0.0040  0.0117  1.0  
4  0.0107  0.0094  1.0  

[5 rows x 61 columns]

In [19]:
data.shape

(208, 61)

In [20]:
np.random.seed(2)
target = np.random.randint(2, size=len(data))

In [21]:
x.shape

(6, 3)

In [22]:
target

array([0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [23]:
perceptron(x,y,0.01)

array([ 0.  ,  0.01,  0.02, -0.01])